# Generated by Django 6.0.6 on 2026-06-21 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T_RelationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='products')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='T_RelationApp.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in process', 'In process'), ('deleverd', 'Deleverd')], max_length=200, null=True)),
                ('total', models.FloatField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='T_RelationApp.productmodel')),
            ],
        ),
    ]
